FROM microsoft/windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Install Java
RUN (new-object System.Net.WebClient).DownloadFile('http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185', 'C:\jre-8u91-windows-x64.exe')
RUN Start-Process -filepath C:\jre-8u91-windows-x64.exe -passthru -wait -argumentlist "/s,INSTALLDIR=c:\Java,/L,install64.log"
RUN del C:\jre-8u91-windows-x64.exe

# Set Environmental Variables
RUN SetX JAVA_HOME "c:\Java" /M
RUN SetX PATH "$env:PATH`;c:\java\bin" /M

#Setup Solr
RUN (new-object System.Net.WebClient).DownloadFile('http://archive.apache.org/dist/lucene/solr/5.4.1/solr-5.4.1.zip', '\solr-5.4.1.zip')
RUN Expand-Archive -Path '\solr-5.4.1.zip' -DestinationPath '\solr' -Force
RUN del '\solr-5.4.1.zip'

RUN Out-File -FilePath "\solr\SolrStart.bat" -InputObject '\solr\solr-5.4.1\bin\solr.cmd start -p 8983 -f' -Encoding oem

#Setup NSSM
RUN (new-object System.Net.WebClient).DownloadFile('https://nssm.cc/release/nssm-2.24.zip', '\nssm-2.24.zip')
RUN Expand-Archive -Path '\nssm-2.24.zip' -DestinationPath '\solr' -Force
RUN del '\nssm-2.24.zip'

RUN Start-Process -FilePath "\solr\nssm-2.24\win64\nssm.exe" -argumentlist 'install solr \solr\SolrStart.bat' -wait

EXPOSE 8983