FROM microsoft/windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Install Java
RUN (new-object System.Net.WebClient).DownloadFile('http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185', 'C:\jre-8u91-windows-x64.exe')
RUN Start-Process -filepath C:\jre-8u91-windows-x64.exe -passthru -wait -argumentlist "/s,INSTALLDIR=c:\Java,/L,install64.log"
RUN del C:\jre-8u91-windows-x64.exe

# Set Environmental Variables
RUN SetX JAVA_HOME "c:\Java" /M
RUN SetX PATH "$env:PATH`;c:\java\bin" /M